# This action fetches .SVD files from ST's website, extracts them and pushes them to 
# the repo

name: fetch-svd

# Runs on a schedule 
on:
    workflow_dispatch:
    schedule:
      - cron: "0 0 * * *"
  
# One job
jobs:
  fetch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: fetch-script
        run: |
          wget https://www.st.com/resource/en/svd/stm32f0_svd.zip    
          unzip stm32f0_svd* -d ./tmp          
          cp -r ./tmp/STM32F0*/* $GITHUB_WORKSPACE/f0
          cp -r ./tmp/Release_Notes.htm $GITHUB_WORKSPACE/ReleaseNotesF0.htm
          rmdir -r tmp
          wget https://www.st.com/resource/en/svd/stm32f1_svd.zip    
          unzip stm32f1_svd* -d ./tmp          
          cp -r ./tmp/STM32F1*/* $GITHUB_WORKSPACE/f1
          cp -r ./tmp/Release_Notes.htm $GITHUB_WORKSPACE/ReleaseNotesF1.htm
          rmdir -r tmp
                    
          git config --global user.name 'svcguy'
          git config --global user.email '5302949+svcguy@users.noreply.github.com'
          git add ReleaseNotes/
          git add f0/
          git add f1/
          git commit -am "Daily Update"
          git push
          
          
          
          

          
