# This action fetches .SVD files from ST's website, extracts them and pushes them to 
# the repo

name: fetch-svd

# Runs on a schedule 
on:
    workflow_dispatch:
    schedule:
      - cron: "0 0 * * *"
  
# One job
jobs:
  fetch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: fetch-script
        run: |
          wget https://www.st.com/resource/en/svd/stm32f0_svd.zip    
          unzip stm32f0_svd* -d ./tmp          
          cp -r ./tmp/STM32F0*/* $GITHUB_WORKSPACE/f0
          cp -r ./tmp/Release_Notes.htm $GITHUB_WORKSPACE/ReleaseNotes/ReleaseNotesF0.htm
          rm -r tmp
          wget https://www.st.com/resource/en/svd/stm32f1_svd.zip    
          unzip stm32f1_svd* -d ./tmp          
          cp -r ./tmp/STM32F1*/* $GITHUB_WORKSPACE/f1
          cp -r ./tmp/Release_Notes.htm $GITHUB_WORKSPACE/ReleaseNotes/ReleaseNotesF1.htm
          rm -r tmp
          wget https://www.st.com/resource/en/svd/stm32f2_svd.zip    
          unzip stm32f2_svd* -d ./tmp          
          cp -r ./tmp/STM32F2*/* $GITHUB_WORKSPACE/f2
          cp -r ./tmp/Release_Notes.htm $GITHUB_WORKSPACE/ReleaseNotes/ReleaseNotesF2.htm
          rm -r tmp
          wget https://www.st.com/resource/en/svd/stm32f3_svd.zip    
          unzip stm32f3_svd* -d ./tmp          
          cp -r ./tmp/STM32F3*/* $GITHUB_WORKSPACE/f3
          cp -r ./tmp/Release_Notes.htm $GITHUB_WORKSPACE/ReleaseNotes/ReleaseNotesF3.htm
          rm -r tmp
          wget https://www.st.com/resource/en/svd/stm32f4_svd.zip    
          unzip stm32f4_svd* -d ./tmp          
          cp -r ./tmp/STM32F4*/* $GITHUB_WORKSPACE/f4
          cp -r ./tmp/Release_Notes.htm $GITHUB_WORKSPACE/ReleaseNotes/ReleaseNotesF4.htm
          rm -r tmp
          wget https://www.st.com/resource/en/svd/stm32f7_svd.zip    
          unzip stm32f7_svd* -d ./tmp          
          cp -r ./tmp/STM32F7*/* $GITHUB_WORKSPACE/f7
          cp -r ./tmp/STM32F7_svd/Release_Notes.htm $GITHUB_WORKSPACE/ReleaseNotes/ReleaseNotesF7.htm
          rm -r tmp
          wget https://www.st.com/resource/en/svd/stm32g0_svd.zip    
          unzip stm32g0_svd* -d ./tmp          
          cp -r ./tmp/STM32G0*/* $GITHUB_WORKSPACE/g0
          cp -r ./tmp/STM32G0_svd/Release_Notes.htm $GITHUB_WORKSPACE/ReleaseNotes/ReleaseNotesG0.htm
          rm -r tmp
          wget https://www.st.com/resource/en/svd/stm32g4_svd.zip    
          unzip stm32g4_svd* -d ./tmp          
          cp -r ./tmp/STM32G4*/* $GITHUB_WORKSPACE/g4
          cp -r ./tmp/STM32G4_svd/Release_Notes.htm $GITHUB_WORKSPACE/ReleaseNotes/ReleaseNotesG4.htm
          rm -r tmp
          wget https://www.st.com/resource/en/svd/stm32h7_svd.zip    
          unzip stm32h7_svd* -d ./tmp          
          cp -r ./tmp/STM32H7*/* $GITHUB_WORKSPACE/h7
          cp -r ./tmp/STM32H7_svd/Release_Notes.htm $GITHUB_WORKSPACE/ReleaseNotes/ReleaseNotesH7.htm
          rm -r tmp
          wget https://www.st.com/resource/en/svd/stm32l0_svd.zip    
          unzip stm32l0_svd* -d ./tmp          
          cp -r ./tmp/STM32L0*/* $GITHUB_WORKSPACE/l0
          cp -r ./tmp/Release_Notes.htm $GITHUB_WORKSPACE/ReleaseNotes/ReleaseNotesL0.htm
          rm -r tmp          
          wget https://www.st.com/resource/en/svd/stm32l1_svd.zip    
          unzip stm32l1_svd* -d ./tmp          
          cp -r ./tmp/STM32L1*/* $GITHUB_WORKSPACE/l1
          cp -r ./tmp/Release_Notes.htm $GITHUB_WORKSPACE/ReleaseNotes/ReleaseNotesL1.htm
          rm -r tmp
          wget https://www.st.com/resource/en/svd/stm32l4_svd.zip    
          unzip stm32l4_svd* -d ./tmp          
          cp -r ./tmp/STM32L4*/* $GITHUB_WORKSPACE/l4
          cp -r ./tmp/Release_Notes.htm $GITHUB_WORKSPACE/ReleaseNotes/ReleaseNotesL4.htm
          rm -r tmp
          wget https://www.st.com/resource/en/svd/stm32l4plus_svd.zip    
          unzip stm32l4plus_svd* -d ./tmp          
          cp -r ./tmp/STM32L4+*/* $GITHUB_WORKSPACE/l4plus
          cp -r ./tmp/Release_Notes.htm $GITHUB_WORKSPACE/ReleaseNotes/ReleaseNotesL4+.htm
          rm -r tmp
          wget https://www.st.com/resource/en/svd/stm32l5_svd.zip    
          unzip stm32l5_svd* -d ./tmp          
          cp -r ./tmp/STM32L5*/* $GITHUB_WORKSPACE/5
          cp -r ./tmp/Release_Notes.htm $GITHUB_WORKSPACE/ReleaseNotes/ReleaseNotesL5.htm
          rm -r tmp
          wget https://www.st.com/resource/en/svd/stm32mp1_svd.zip    
          unzip stm32mp1_svd* -d ./tmp          
          cp -r ./tmp/STM32MP1*/* $GITHUB_WORKSPACE/mp1
          cp -r ./tmp/Release_Notes.htm $GITHUB_WORKSPACE/ReleaseNotes/ReleaseNotesMP1.htm
          rm -r tmp
          wget https://www.st.com/resource/en/svd/stm32wb_svd.zip    
          unzip stm32wb_svd* -d ./tmp          
          cp -r ./tmp/STM32WB*/* $GITHUB_WORKSPACE/wb
          cp -r ./tmp/Release_Notes.htm $GITHUB_WORKSPACE/ReleaseNotes/ReleaseNotesWB.htm
          rm -r tmp
          wget https://www.st.com/resource/en/svd/stm32wl_svd.zip    
          unzip stm32wl_svd* -d ./tmp          
          cp -r ./tmp/STM32WL*/* $GITHUB_WORKSPACE/wl
          cp -r ./tmp/Release_Notes.htm $GITHUB_WORKSPACE/ReleaseNotes/ReleaseNotesWL.htm
          rm -r tmp
                    
          git config --global user.name 'svcguy'
          git config --global user.email '5302949+svcguy@users.noreply.github.com'
          git add ReleaseNotes/
          git add f0/
          git add f1/
          git add f2/
          git add f3/
          git add f4/
          git add f7/
          git add g0/
          git add g4/
          git add h7/
          git add l0/
          git add l1/
          git add l4/
          git add l4plus/
          git add l5/
          git add mp1/
          git add wb/
          git add wl/
          git commit -am "Daily Update"
          git push
          
          
          
          

          
